config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "category" => "pages#category"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :mesures, only: %i[index show new create update destroy] do
    resources :comments, only: %i[create]
  end

  resources :comments, only: %i[destroy] do
    member do
      patch "upvote"
      patch "downvote"
    end
    resources :sub_comments, only: %i[create]
  end

  resources :mesures, only: [] do
    member do
      patch "upvote"
    end
  end

  resources :sub_comments, only: %i[destroy] do
    member do
      patch "upvote"
      patch "downvote"
    end
  end
  resources :chatrooms , only: [] do
    resources :messages, only: :create
  end
  resources :observations, only: %i[index new create]

  resources :users, only: [] do
    resources :notifications, only: %i[create]
  end
  delete "/users/:user_id/notifications/destroy" => "notifications#destroy"

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :mesure
  has_many :sub_comments, dependent: :destroy

  acts_as_votable

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_mesure, only: %i[create]
  before_action :find_comment, only: %i[destroy upvote downvote]

  def create
    @comment = Comment.new
    @comment.user = current_user
    @comment.mesure = @mesure
    @comment.content = params[:comment][:content]
    if @comment.save
      redirect_to @mesure, notice: 'Le commentaire a bien été envoyé.'
    end
  end

  def destroy
    @comment.destroy
    redirect_to request.referer, status: :see_other
  end

  def upvote
    if current_user.voted_up_on? @comment
      @comment.unvote_by current_user
    else
      @comment.upvote_by current_user
    end
    upvote_html = render_to_string(partial: 'comments/upvote_link', locals: { comment: @comment }, formats: :html)
    downvote_html = render_to_string(partial: 'comments/downvote_link', locals: { comment: @comment }, formats: :html)
    render json: { upvote_html: upvote_html, downvote_html: downvote_html }
  end

  def downvote
    if current_user.voted_down_on? @comment
      @comment.unvote_by current_user
    else
      @comment.downvote_by current_user
    end
    upvote_html = render_to_string(partial: 'comments/upvote_link', locals: { comment: @comment }, formats: :html)
    downvote_html = render_to_string(partial: 'comments/downvote_link', locals: { comment: @comment }, formats: :html)
    render json: { upvote_html: upvote_html, downvote_html: downvote_html }
  end

  private

  def find_mesure
    @mesure = Mesure.find(params[:mesure_id])
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def comments_params
    params.require(:comment).permit(:content, :mesure_id)
  end
end

app/views/comments/_downvote_link.html.erb
<%= content_tag "div", id: "downvote-#{comment.id}", data: { comment_vote_target: 'downvoteArea' } do %>
  <%= link_to downvote_comment_path(comment), data: { turbo_method: :patch, action: "click->comment-vote#vote", disable_with: "voting..." }, class: "comment-votes" do %>
    <% if current_user %>
      <% if current_user.voted_down_on? comment%>
        <%= comment.cached_votes_down %><i class="fas fa-thumbs-down"></i>
      <% else %>
        <%= comment.cached_votes_down %><i class="far fa-thumbs-down"></i>
      <% end %>
    <% else %>
      <%= comment.cached_votes_down %><i class="far fa-thumbs-down"></i>
    <% end %>
  <% end %>
<% end %>

app/views/comments/_upvote_link.html.erb
<%= content_tag "div", id: "upvote-#{comment.id}", data: { comment_vote_target: 'upvoteArea' } do %>
  <%= link_to upvote_comment_path(comment), data: { turbo_method: :patch, action: "click->comment-vote#vote", disable_with: "voting..." }, class: "comment-votes" do %>
    <% if current_user %>
      <% if current_user.voted_up_on?(comment) %>
        <%= comment.cached_votes_up %><i class="fas fa-thumbs-up"></i>
      <% else %>
        <%= comment.cached_votes_up %><i class="far fa-thumbs-up"></i>
      <% end %>
    <% else %>
      <%= comment.cached_votes_up %><i class="far fa-thumbs-up"></i>
    <% end %>
  <% end %>
<% end %>