config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "category" => "pages#category"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :mesures, only: %i[index show new create update destroy] do
    resources :comments, only: %i[create]
  end

  resources :comments, only: %i[destroy] do
    member do
      patch "upvote"
      patch "downvote"
    end
    resources :sub_comments, only: %i[create]
  end

  resources :mesures, only: [] do
    member do
      patch "upvote"
    end
  end

  resources :sub_comments, only: %i[destroy] do
    member do
      patch "upvote"
      patch "downvote"
    end
  end
  resources :chatrooms , only: [] do
    resources :messages, only: :create
  end
  resources :observations, only: %i[index new create]

  resources :users, only: [] do
    resources :notifications, only: %i[create]
  end
  delete "/users/:user_id/notifications/destroy" => "notifications#destroy"

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/models/mesure.rb
class Mesure < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy

  attr_accessor :sort_by, :order, :mayor

  acts_as_votable

  validates :title, presence: true
  validates :content, presence: true
  validates :category, presence: true
end

app/controllers/mesures_controller.rb
class MesuresController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :find_mesure, only: %i[show update destroy upvote]

  def index
    @page = params[:page].to_i if params[:page].present?
    allmesures = Mesure.includes(:user).includes(:category).all
    mesures = allmesures

    if params[:mesure].present?
      mesures = mesures.where(user: {mayor: true}) if params[:mesure][:mayor] == "1"
      category = Category.find(params[:mesure][:category_id]) if params[:mesure][:category_id].present?
      mesures = mesures.where(category: {name: category.name}) if params[:mesure][:category_id].present?
      mesures = mesures.where(mesures: {status: params[:mesure][:status]}) if params[:mesure][:status].present?
    end

    if params[:mesure].present?
      sens = "desc"
      sens = "asc" if params[:mesure][:order] == "Croissant"
      if params[:mesure][:sort_by] == "Nombre de soutien"
        mesures = mesures.order(cached_votes_up: sens.to_sym)
      elsif params[:mesure][:sort_by] == "Statut"
        mesures = mesures.order(status: sens.to_sym)
      else
        mesures = mesures.order(created_at: sens.to_sym)
      end
    end

    @pages = (1..(mesures.count / 10))

    if @page.nil?
      @mesures = mesures[0..9]
    else
      @mesures = mesures[((@page - 1) * 10)..((@page * 10) - 1)]
    end

    @comments = Comment.includes(:mesure).includes(:user).all.order(created_at: :desc).last(10)
  end

  def show
    @comments = @mesure.comments.includes(:sub_comments).order(created_at: :desc)
    @comment = Comment.new
    @sub_comment = SubComment.new
  end

  def new
    @mesure = Mesure.new
  end

  def update
    if current_user.mayor
      @mesure.status =  params[:m]
      @mesure.save
      redirect_to mesure_path(@mesure), success: "La mesure a bien été #{params[:m].downcase}e"
    else
      redirect_to mesure_path(@mesure), status: :unauthorized
    end
  end

  def destroy
    @mesure.destroy
  end

  def upvote
    if current_user.voted_up_on? @mesure
      @mesure.unvote_by current_user
    else
      @mesure.upvote_by current_user
    end
    mesure_upvote_html = render_to_string(partial: 'mesures/mesure_upvote_link', locals: { mesure: @mesure }, formats: :html)
    render json: { mesure_upvote_html: mesure_upvote_html }
  end

  def create
    @category = Category.find(params[:mesure][:category_id])
    @mesure = Mesure.new(mesures_params)
    @mesure.category = @category
    @mesure.user = current_user
    @mesure.status = "En cours de concertation"
    if @mesure.save
      redirect_to @mesure, success: "La mesure a bien été créée"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def find_mesure
    @mesure = Mesure.find(params[:id])
  end

  def mesures_params
    params.require(:mesure).permit(:title, :content, :category_id)
  end
end

app/views/mesures/_mesure_show_card.html.erb
<div class="white-box mt-3">
  <div class="titre m-2 mb-3">
    <h4><%= @mesure.title %></h4>
  </div>
  <div class="d-flex justify-content-center">
    <div class="line-1"></div>
  </div>
  <div class="like d-flex">
    <div class="user">
      <p>Proposé par <%= @mesure.user.first_name %> <%= @mesure.user.last_name %> </p>
    </div>
    <%= render partial: "mesures/mesure_upvote_link", locals: {mesure: @mesure } %>
  </div>
  <div class="category-status d-flex">
    <div class="mid-item">
      <i class="fa-solid fa-list fa-xl"></i> <%= @mesure.category.name %>
    </div>
    <div class="mid-item">
      <% if @mesure.status == "En cours de concertation" %>
        <i class="fa-regular fa-comment-dots text-primary"></i>
      <% elsif @mesure.status == "Refusé" %>
        <i class="fa-solid fa-xmark text-danger"></i>
      <% elsif @mesure.status == "Validé" %>
        <i class="fa-regular fa-square-check text-success"></i>
      <% end %>
      <%= @mesure.status %>
    </div>
  </div>
  <div class="description">
    <%= @mesure.content %>
  </div>
  <%= render partial: "shared/validation_button", locals: { mesure: @mesure } %>
</div>

app/views/mesures/_mesure_upvote_link.html.erb
<div data-controller="mesure-upvote" data-mesure-upvote-user-value="<%= current_user ? current_user.id : 0 %>">
  <%= content_tag "div", id: "upvote-#{@mesure.id}", data: { mesure_upvote_target: 'mesureupvoteArea'} do %>
    <%= link_to upvote_mesure_path(@mesure), data: { turbo_method: :patch, action: "click->mesure-upvote#vote", disable_with: "voting..." } do %>
      <% if current_user %>
        <% if current_user.voted_up_on? @mesure %>
          <div class="like-box">
            <div class="number">
              <p> <%= @mesure.cached_votes_up %> soutiens</p>
            </div>
            <i class="fas fa-heart logo"></i>
          </div>
        <% else %>
          <div class="like-box">
            <div class="number">
              <p> <%= @mesure.cached_votes_up %> soutiens</p>
            </div>
            <i class="far fa-heart logo"></i>
          </div>
        <% end %>
      <% else %>
        <div class="like-box">
          <div class="number">
            <p> <%= @mesure.cached_votes_up %> soutiens</p>
          </div>
          <i class="far fa-heart logo"></i>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>
<%# <%= render partial: "mesures/mesure_upvote_link", locals: {mesure: @mesure } %>
<%# A AFFICHER LA OU ON VEUT %>

<script>
  document.querySelector('.like-box').addEventListener('click', function(event) {
    var likeBox = event.currentTarget;
    likeBox.classList.toggle('clicked');
  });
</script>

app/views/mesures/index.html.erb
<%= link_to "Ajouter une mesure", new_mesure_path, class:"btn btn-primary mt-3 ms-3" %>
<div class="m-0 row g-4">
  <%= render partial: "shared/small_mesure_card", locals: {mesures: @mesures, pages: @pages} %>
  <%= render partial: "shared/messages_tab", locals: {comments: @comments } %>
</div>

app/views/mesures/new.html.erb
<div data-controller="new-mesure">
  <%= simple_form_for @mesure do |f| %>
    <div class="row gy-4 mx-2 mt-3">
      <h2 class='text-center m-1 blue-text'> Proposer une nouvelle <strong>mesure</strong></h2>
      <%= f.input :title, class: "flex-grow-1", label: false, placeholder: "Entrez le titre de votre mesure" %>
      <div class="col-4 m-0">
        <%= f.association :category, input_html: { 'data-action': "input->new-mesure#show", 'data-new-mesure-target': 'input', class: "mb-3" }, label: false, include_blank: "Choisissez une catégorie"%>
        <%= f.input :content, label: false, placeholder: "Décrivez votre mesure", input_html: { style: 'height: 300px;' } %>
        <%= f.button :submit, "Proposer la mesure", class: "btn btn-primary" %>
      </div>
      <div class="col-8 mt-0">
      <div class="blue-box flex-grow-1 h-100">
          <h3 class="p-1">Les mesures déjà proposées pour cette catégorie</h3>
        <div data-new-mesure-target= "container">
        <p class="fst-italic text-center mt-3"> Choisissez une catégorie pour afficher les mesures </p>
        </div>
      </div>
      </div>
    <% end %>
  </div>
</div>

app/views/mesures/show.html.erb
<div class="row">
  <div class="col top">
    <div class="d-flex col mb-1">
      <%= render partial: "mesures/mesure_show_card", locals: {mesure: @mesure } %>
    </div>
    <div class="d-flex align-items-center blue-text gap-2 mt-4">
      <%= image_tag "#{@mesure.category.name}.svg" %>
      <h5>Cette mesure vise à améliorer la catégorie <strong><%=@mesure.category.name%></strong> au sein de la commune. Soutenez cette initiative si vous souhaitez qu'elle soit étudiée.</h5>
    </div>
  </div>
  <%= render partial: "shared/comments_area", locals: {mesure: @mesure, comments: @comments, comment: @comment } %>
</div>