config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "category" => "pages#category"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :mesures, only: %i[index show new create update destroy] do
    resources :comments, only: %i[create]
  end

  resources :comments, only: %i[destroy] do
    member do
      patch "upvote"
      patch "downvote"
    end
    resources :sub_comments, only: %i[create]
  end

  resources :mesures, only: [] do
    member do
      patch "upvote"
    end
  end

  resources :sub_comments, only: %i[destroy] do
    member do
      patch "upvote"
      patch "downvote"
    end
  end
  resources :chatrooms , only: [] do
    resources :messages, only: :create
  end
  resources :observations, only: %i[index new create]

  resources :users, only: [] do
    resources :notifications, only: %i[create]
  end
  delete "/users/:user_id/notifications/destroy" => "notifications#destroy"

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/views/shared/_comment.html.erb
<div class="blue-box col-8 mt-3 mb-3">
  <%= simple_form_for [@mesure, @comment] do |f| %>
    <%= f.input :content, label: 'Votre commentaire' %>
    <div class="form-actions my-2 text-end">
      <%= f.button :submit, "Envoyer", class: "btn btn-primary" %>
    </div>
  <% end %>
  <h5><%= comments.count %> commentaires</h5>
  <% comments.each do |comment| %>
    <div class="comment-area">
      <div class="user-name-time-comment">
        <div class="d-flex">
          <h6 class="name-comment"><%= comment.user.first_name %> <%= comment.user.last_name %> </h6>
          <p class="time-comment">
            <% minutes = ((Time.now - comment.created_at)/60).round %>
            <% if minutes < 60 %>
              <p class="time">Il y a <%= minutes %> min</p>
            <% elsif (minutes/60).round < 24%>
              <p class="time">Il y a <%= (minutes/60).round %> h </p>
            <% else %>
              <p class="time">Il y a <%= (minutes/60/24).round %> j </p>
            <% end %>
          </p>
        </div>
        <% if comment.user == current_user %>
          <%= link_to comment_path(comment), data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr?" } do %>
            <i class="fa-regular fa-trash-can"></i>
          <% end %>
        <% end %>
      </div>
      <p class="content"><%= comment.content %></p>
      <div class="answers-like">
        <div class="answers">
          <% if comment.sub_comments.present? %>
            <button class="btn btn-link btn-sm" onclick="toggleSubComments(<%= comment.id %>)"><%= comment.sub_comments.count %> réponses</button>
          <% end %>
        </div>
        <div class="votes">
          <button class="btn btn-link btn-sm" onclick="toggleReplyForm(<%= comment.id %>)">Répondre</button>
            <div data-controller="comment-vote" class="comment-votes" data-comment-vote-user-value="<%= current_user ? current_user.id : 0 %>" >
              <%= render 'comments/upvote_link', comment: comment %>
              <%= render 'comments/downvote_link', comment: comment %>
            </div>
        </div>
      </div>
    </div>
    <div id="reply-form-container-<%= comment.id %>" style="display: none" class="col-md-12 sub-comment-area flex-end">
      <div class="row justify-content-end">
        <div class="col-10">
          <%= simple_form_for [comment, @sub_comment] do |f| %>
            <%= f.input :content, label: 'Votre réponse' %>
            <div class="form-actions my-2 text-end">
              <%= f.button :submit, "Envoyer", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div id="sub-comments-container-<%= comment.id %>" style="display: none" class="comment-votes">
      <%= render partial: "shared/sub_comment", locals: {sub_comments: comment.sub_comments } %>
    </div>
  <% end %>
</div>

app/views/shared/_comments_area.html.erb
<div class="col-md-8">
  <%= render partial: "shared/comment", locals: {comments: @comments, sub_comments: @sub_comments } %>
</div>
<script>
  function toggleSubComments(commentId) {
    var subCommentsContainer = document.getElementById('sub-comments-container-' + commentId);
    if (subCommentsContainer.style.display === 'none') {
      subCommentsContainer.style.display = 'block';
    } else {
      subCommentsContainer.style.display = 'none';
    }
  }

  function toggleReplyForm(commentId) {
  var formContainer = document.getElementById('reply-form-container-' + commentId);
  formContainer.style.display = (formContainer.style.display === 'none') ? 'block' : 'none';
  }
</script>

app/views/shared/_filter_bar.html.erb
<div data-controller="filter">
  <%= simple_form_for Mesure.new, url: mesures_path, method: :get do |f| %>
    <div class="item d-flex justify-content-evenly align-items-center">
      <p>Filter par :</p>
      <div class="d-flex align-items-center gap-2 row-gap-0">
        <%= f.association :category, label: false, include_blank: "Catégorie", selected: params.dig(:mesure,:category_id), input_html: {'data-action': "input->filter#click"} %>
        <%= f.input :status, as: :select, collection: ["En cours de concertation","Refusé","Validé"],label: false, include_blank: "Statut", selected: params.dig(:mesure,:status), input_html: {'data-action': "input->filter#click"}%>
        <%= f.input :mayor, as: :boolean ,label: 'Mesures du maire',legend: false,selected: params.dig(:mesure,:user_id), class: "m-0", input_html: { checked: (params.dig(:mesure,:mayor) == "1"), 'data-action': "input->filter#click" } %>
      </div>
    </div>
    <div class="item align-items-center justify-content-end gap-2">
      <p>Trier par :</p>
      <%= f.input :sort_by, as: :select, collection: ["Nombre de soutien","Date de création","Statut"],label: false,selected: (params.dig(:mesure,:sort_by) || "Date de création"), input_html: {'data-action': "input->filter#click"} %>
      <%= f.input :order, as: :select, collection: ["Croissant","Décroissant"], label: false,selected: (params.dig(:mesure,:order) || "Décroissant"), input_html: {'data-action': "input->filter#click"} %>
      <%= f.button :submit, class: "d-none", 'data-filter-target': 'button' %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if success %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= success %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_legende.html.erb
<div class="light-grey p-1">
  <div class="d-flex gap-1 my-0">
    <i class="fa-regular fa-comment-dots text-primary"></i>
    <p class="m-0">: En cours de concertation </p>
  </div>
  <div class="d-flex gap-1 my-0">
    <i class="fa-solid fa-xmark text-danger"></i>
    <p class="m-0">: Refusée</p>
  </div>
  <div class="d-flex gap-1 my-0">
    <i class="fa-regular fa-square-check text-success"></i>
    <p class="m-0">: Validée</p>
  </div>
</div>

app/views/shared/_mapbox.html.erb
<div class="col-md-5 box-shadow p-0">
<h3 class="titre-map">Observations Citoyennes</h3>
    <div style="width: 100%; flex: grow;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    <div class="position-bottom-map justify-content-between">
      <%= link_to "Faire une observation", new_observation_path, class: "btn btn-danger" if btn_red%>
    </div>
  </div>

app/views/shared/_message.html.erb
<div id="message-<%= message.id %>">
  <small>
    <strong><%= message.user.first_name %> <%= message.user.last_name %></strong>
    <i><%= message.created_at.strftime("%e %b à %H:%M") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/shared/_mesure_box_new.html.erb
<div class="animate__animated animate__fadeIn">
<% mesures.each do |mesure| %>
  <%= link_to mesure, class: "item flex-column" do %>
    <div class="d-flex my-2">
      <h5 class="text-start ">
        <%= mesure.title.slice(0..55) %><%= "..." if mesure.title.length > 55 %>
      </h5>
      <div class="right-corner">
        <%= render partial: "shared/mesure_likes", locals: {mesure: mesure } %>
      </div>
    </div>
    <div class="d-flex my-0 justify-content-between me-2">
      <div class="my-2 col-8">
        <p class="fst-italic">"<%= mesure.content.slice(0..250) %><%= "..." if mesure.content.length > 250 %>"</p>
      </div>
      <div class="d-flex align-items-center gap-1 flex-nowrap">
        <% if mesure.status == "En cours de concertation" %>
          <p>Statut: </p>
          <i class="fa-regular fa-comment-dots text-primary"></i>
          <p class="flex-nowrap">depuis <%= mesure.created_at.strftime("%e %b à %H:%M") %> </p>
        <% elsif mesure.status == "Refusé" %>
          <p>Statut: </p>
          <i class="fa-solid fa-xmark text-danger"></i>
        <% elsif mesure.status == "Validé" %>
          <p>Statut: </p>
          <i class="fa-regular fa-square-check text-success"></i>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>
</div>

app/views/shared/_mesure_likes.html.erb
<div class="small-like-box">
  <i class="fa-solid fa-heart small-logo text-danger"></i>
  <div class="small-number">
    <%= mesure.cached_votes_up %>
  </div>
</div>

app/views/shared/_mesures_box.html.erb
<div class="blue-box <%= cl %> ">
  <div class="mb-2 pb-2">
    <% mesures.each do |mesure| %>
      <%= link_to mesure, class: "item flex-column" do %>
        <div class="d-flex my-2">
          <h5 class="text-start ">
            <%= mesure.title.slice(0..55) %><%= "..." if mesure.title.length > 55 %>
          </h5>
          <div class="right-corner">
            <%= render partial: "shared/mesure_likes", locals: {mesure: mesure } %>
          </div>
        </div>
        <div class="d-flex my-0 justify-content-between me-2">
          <p class="
          <%= "red" if ["Environnement","Santé","Finances"].include?(mesure.category.name)%>
          <%= "blue" if ["Solidarité", "Sport", "Inclusion", "Jeunesse"].include?(mesure.category.name)%>
          <%= "green" if ["Culture", "Patrimoine", "Tourisme", "Mobilier"].include?(mesure.category.name)%>
          <%= "yellow" if mesure.category.name == "Autre"%>
          "><%= mesure.category.name %></p>
          <div class="d-flex align-items-center gap-1">
            <% if mesure.status == "En cours de concertation" %>
              <p>Statut: </p>
              <i class="fa-regular fa-comment-dots text-primary"></i>
              <p>depuis <%= mesure.created_at.strftime("%e %b à %H:%M") %> </p>
            <% elsif mesure.status == "Refusé" %>
              <p>Statut: </p>
              <i class="fa-solid fa-xmark text-danger"></i>
            <% elsif mesure.status == "Validé" %>
              <p>Statut: </p>
              <i class="fa-regular fa-square-check text-success"></i>
            <% end %>
          </div>
        </div>
        <div class="my-2">
          <p class="fst-italic mx-0">"<%= mesure.content.slice(0..250) %><%= "..." if mesure.content.length > 250 %>"</p>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="justify-content-between d-flex">
    <div class="d-flex align-items-end mb-2 ms-2">
      <%= link_to "Afficher plus", mesures_path(mesure: parameter), class: "btn btn-primary" %>
    </div>
    <%= render partial: "shared/legende" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid mx-4">
    <div class="d-flex align-items-center">
      <%= link_to "/", class: "navbar-brand d-flex align-items-center" do %>
        <%= image_tag "logo.png" %>
        <h3 class="m-0 ms-2">We</h3>
        <h3 class="m-0" id="public">public</h3>
      <% end %>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <li class="nav-item mx-2 d-flex align-items-center">
              <%= link_to "Voir les mesures", mesures_path, class: "dropdown-item" %>
          </li>
        <li class="nav-item mx-2 d-flex align-items-center">
              <%= link_to "Proposer une mesure", new_mesure_path, class: "dropdown-item" %>
          </li>
          <li class="nav-item mx-2 d-flex align-items-center">
                  |
          </li>
          <div class="nav-item mx-2 d-flex align-items-center">
          Bonjour <%= current_user.first_name %>
          </div>
          <li class="nav-item dropdown">
            <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Deconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="d-flex align-items-center">
            <h5 class="m-0">|</h5>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_observation_window.html.erb
<div class="container font-raleway">
<h5 class="text-center"><%= observation.title %></h5>
<div class="d-flex justify-content-between">
<p class="mb-2"><%= observation.user.first_name %> <%= observation.user.last_name %></p>
<p class="mb-2"> le <%= observation.created_at.strftime("%e %b %Y") %></p>
</div>
<div class="d-flex gap-4  border-bottom border-dark-subtle justify-content-end">
<p class="mb-2
          <%= "red" if ["Environnement","Santé","Finances"].include?(observation.category.name)%>
          <%= "blue" if ["Solidarité", "Sport", "Inclusion", "Jeunesse"].include?(observation.category.name)%>
          <%= "green" if ["Culture", "Patrimoine", "Tourisme", "Mobilier"].include?(observation.category.name)%>
          <%= "yellow" if observation.category.name == "Autre"%>
          "><%= observation.category.name %></p>
</div>
<p class="fst-italic mt-1"> <%= observation.description %></p>
</div>

app/views/shared/_small_mesure_card.html.erb
<div class="col-md-8">
  <div class="blue-box">
    <h3>Mesures proposées</h3>
    <%= render partial: "shared/filter_bar" %>
    <% mesures.each do |mesure| %>
      <%= link_to mesure, class: "item flex-column" do %>
        <div class="d-flex mt-1">
          <h3 class="text-start">
            <%= mesure.title.slice(0..40) %><%= "..." if mesure.title.length > 40 %>
          </h3>
          <div class="right-corner">
            <%= render partial: "shared/mesure_likes", locals: {mesure: mesure } %>
          </div>
        </div>
        <div class="d-flex my-0 justify-content-between me-2">
          <p class="
          <%= "red" if ["Environnement","Santé","Finances"].include?(mesure.category.name)%>
          <%= "blue" if ["Solidarité", "Sport", "Inclusion", "Jeunesse"].include?(mesure.category.name)%>
          <%= "green" if ["Culture", "Patrimoine", "Tourisme", "Mobilier"].include?(mesure.category.name)%>
          <%= "#F9F3CC" if mesure.category.name == "Autre"%>
          "><%= mesure.category.name %></p>
          <div class="d-flex align-items-center gap-1">
          <% if mesure.status == "En cours de concertation" %>
           <p>Statut: </p> <i class="fa-regular fa-comment-dots text-primary"></i><p>depuis <%= mesure.created_at.strftime("%e %b à %H:%M") %> </p>
          <% elsif mesure.status == "Refusé" %>
          <p>Statut: </p><i class="fa-solid fa-xmark text-danger"></i>
          <% elsif mesure.status == "Validé" %>
          <p>Statut: </p><i class="fa-regular fa-square-check text-success"></i>
          <% end %>
          </div>
        </div>
        <div class="my-2">
          <p class="fst-italic mx-0">"<%= mesure.content.slice(0..250) %><%= "..." if mesure.content.length > 250 %>"</p>
        </div>
      <% end %>
    <% end %>
    <div class="d-flex justify-content-end">
      <% pages.each do |n| %>
        <div class="page-link
        <% if n == params[:page].to_i || (!params[:page].present? && n == 1) %>
        <%= " active" %>
        <% end %>">
          <%= link_to "#{n}", mesures_path(mesure: {mayor: params.dig(:mesure,:mayor), category_id: params.dig(:mesure,:category_id), sort_by: params.dig(:mesure,:sort_by), order: params.dig(:mesure,:order)},page: n)%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_validation_button.html.erb
<% if current_user && current_user.mayor && mesure.status == "En cours de concertation"%>
  <div class="gap-2 boutons">
    <%= link_to "Valider", mesure_path(mesure, m: "Validé"), class:"btn btn-primary btn-validation small-bouton",data: { turbo_method: :patch, turbo_confirm: "Etes vous sûr de vouloir changer le statut de cette mesure ?" } %>
    <%= link_to "Refuser", mesure_path(mesure, m:"Refusé"), class:"btn btn-danger btn-validation small-bouton",data: { turbo_method: :patch, turbo_confirm: "Etes vous sûr de vouloir changer le statut de cette mesure ?" } %>
  </div>
<% else %>
  <div class="gap-1 boutons">
    <i class="fa-solid fa-share-nodes"></i><p class="me-1">Partager</p>
    <i class="fa-solid fa-plus"></i><p>Suivre</p>
  </div>
<% end %>