config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "category" => "pages#category"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :mesures, only: %i[index show new create update destroy] do
    resources :comments, only: %i[create]
  end

  resources :comments, only: %i[destroy] do
    member do
      patch "upvote"
      patch "downvote"
    end
    resources :sub_comments, only: %i[create]
  end

  resources :mesures, only: [] do
    member do
      patch "upvote"
    end
  end

  resources :sub_comments, only: %i[destroy] do
    member do
      patch "upvote"
      patch "downvote"
    end
  end
  resources :chatrooms , only: [] do
    resources :messages, only: :create
  end
  resources :observations, only: %i[index new create]

  resources :users, only: [] do
    resources :notifications, only: %i[create]
  end
  delete "/users/:user_id/notifications/destroy" => "notifications#destroy"

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/models/sub_comment.rb
class SubComment < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  acts_as_votable

  validates :content, presence: true
end

app/controllers/sub_comments_controller.rb
class SubCommentsController < ApplicationController
  before_action :find_comment, only: %i[create]

  before_action :find_sub_comment, only: %i[destroy]

  def create
    @sub_comment = SubComment.new
    @sub_comment.user = current_user
    @sub_comment.comment = @comment
    @sub_comment.content = params[:sub_comment][:content]
    if @sub_comment.save
      redirect_to @comment.mesure, notice: 'Le commentaire a bien été envoyé.'
    end
  end

  def upvote
    @sub_comment = SubComment.find(params[:id])
    if current_user.voted_up_on? @sub_comment
      @sub_comment.unvote_by current_user
    else
      @sub_comment.upvote_by current_user
    end
    sub_upvote_html = render_to_string(partial: 'sub_comments/sub_upvote_link', locals: { sub_comment: @sub_comment }, formats: :html)
    sub_downvote_html = render_to_string(partial: 'sub_comments/sub_downvote_link', locals: { sub_comment: @sub_comment }, formats: :html)
    render json: { sub_upvote_html: sub_upvote_html, sub_downvote_html: sub_downvote_html }
  end

  def downvote
    @sub_comment = SubComment.find(params[:id])
    if current_user.voted_down_on? @sub_comment
      @sub_comment.unvote_by current_user
    else
      @sub_comment.downvote_by current_user
    end
    sub_upvote_html = render_to_string(partial: 'sub_comments/sub_upvote_link', locals: { sub_comment: @sub_comment }, formats: :html)
    sub_downvote_html = render_to_string(partial: 'sub_comments/sub_downvote_link', locals: { sub_comment: @sub_comment }, formats: :html)
    render json: { sub_upvote_html: sub_upvote_html, sub_downvote_html: sub_downvote_html }
  end

  def destroy
    @sub_comment.destroy
    redirect_to request.referer, status: :see_other
  end

  private

  def find_comment
    @comment = Comment.find(params[:comment_id])
  end

  def find_sub_comment
    @sub_comment = SubComment.find(params[:id])
  end

  def find_mesure
    @mesure = Mesure.find(params[:mesure_id])
  end

  def sub_comments_params
    params.require(:sub_comment).permit(:content, :comment_id, :mesure_id)
  end
end

app/views/sub_comments/_sub_downvote_link.html.erb
  <%= content_tag "div", id: "downvote-#{sub_comment.id}", data: { sub_comment_vote_target: 'subdownvoteArea'} do %>
    <%= link_to downvote_sub_comment_path(sub_comment), data: { turbo_method: :patch, action: "click->sub-comment-vote#vote", disable_with: "voting..." }, class: "sub-comment-votes" do %>
      <% if current_user %>
        <% if current_user.voted_down_on? sub_comment %>
          <%= sub_comment.cached_votes_down %><i class="fas fa-thumbs-down"></i>
        <% else %>
          <%= sub_comment.cached_votes_down %><i class="far fa-thumbs-down"></i>
        <% end %>
      <% else %>
        <%= sub_comment.cached_votes_down %><i class="far fa-thumbs-down"></i>
      <% end %>
    <% end %>
<% end %>

app/views/sub_comments/_sub_upvote_link.html.erb
  <%= content_tag "div", id: "upvote-#{sub_comment.id}", data: { sub_comment_vote_target: 'subupvoteArea'} do %>
    <%= link_to upvote_sub_comment_path(sub_comment), data: { turbo_method: :patch, action: "click->sub-comment-vote#vote", disable_with: "voting..." }, class: "sub-comment-votes" do %>
      <% if current_user %>
        <% if current_user.voted_up_on? sub_comment %>
          <%= sub_comment.cached_votes_up %><i class="fas fa-thumbs-up"></i>
        <% else %>
          <%= sub_comment.cached_votes_up %><i class="far fa-thumbs-up"></i>
        <% end %>
      <% else %>
        <%= sub_comment.cached_votes_up %><i class="far fa-thumbs-up"></i>
      <% end %>
    <% end %>
  <% end %>